kubectl apply -f backend-config-map.yaml
kubectl apply -f backend-deployment.yaml
kubectl apply -f backend-route.yaml
kubectl apply -f backend-service.yaml
kubectl apply -f frontend-config-map.yaml
kubectl apply -f frontend-deployment.yaml
kubectl apply -f frontend-route.yaml
kubectl apply -f frontend-service.yaml
kubectl apply -f database-deployment.yaml
kubectl apply -f database-service.yaml
kubectl apply -f database-secret.yaml