apiVersion: v1
kind: Secret
metadata:
  name: counter-database
  labels:
    project: counter
    component: database
type: Opaque
data:
  database-name: Y291bnRlci1kYXRhYmFzZQ==
  database-user: Y291bnRlci11c2Vy
  database-password: cGFzc3dvcmQxMjM0