kind: Deployment
apiVersion: apps/v1
metadata:
  name: counter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-backend
          image: ghcr.io/doctorprogrammer/counter-frontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: backend-url
            - name: npm_config_cache
              value: ./.npm-cache
---
apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
spec:
  selector:
    app: counter-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  backend-url: "https://counter-backend-243635-robtra.apps.exoscale-ch-gva-2-0.appuio.cloud"